#!/usr/bin/env ruby

require 'yajl'
require 'yaml'
require 'optparse'

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))

require 'chef/cache'
require 'chef/version'

class Poller
  attr_reader :options

  def initialize
    @options = {}

    optparse = OptionParser.new do |opts|
      opts.banner = "Usage: #{$0}"

      opts.on_tail('-h', '--help', 'Print this help message') do
        puts opts
        exit
      end
      opts.on('-s SLEEP',
              "Specify a sleep interval that will infinitely loop execution") do |s|
        @options[:sleep] = s
      end
    end
    optparse.parse!
  end

  def cache
    @cache ||= Chef::Cache.new()
  end

  def run
    cache.update
  end
end

if File.absolute_path($0) == File.absolute_path(__FILE__)
  poller = Poller.new
  poller.run

  while poller.options[:sleep]
    puts "Sleep time set to #{poller.options[:sleep]}"
    sleep poller.options[:sleep].to_i
    poller.run
  end
end
