source "https://supermarket.chef.io"

metadata

cookbook 'delivery-truck', git: 'https://github.com/opscode-cookbooks/delivery-truck.git'

# TODO: (jtimberman) remove this pin when ChefDK is updated to Chef
# 13. internal ref issue POOL-571.
cookbook 'delivery-sugar', github: 'chef-cookbooks/delivery-sugar', ref: '89da6f837e73e299a6a8f0122831031747f5d3a0'
cookbook 'cia_infra', git: 'git@github.com:chef-cookbooks/cia_infra.git'
cookbook 'oc-users', git: 'git@github.com:opscode-cookbooks/oc-users.git'
cookbook 'route53', git: 'https://github.com/cwebberOps/route53.git', branch: 'pdb/nononokogiri'
cookbook 'brightbox-ruby', github: 'Padgett/brightbox-ruby-cookbook', branch: 'boolean-generate-binstubs'
cookbook 'habitat-build', git: 'https://github.com/chef-cookbooks/habitat-build'
