source "https://supermarket.chef.io"

metadata

cookbook 'delivery-truck', git: 'https://github.com/opscode-cookbooks/delivery-truck.git'
cookbook 'delivery-sugar', github: 'chef-cookbooks/delivery-sugar'
cookbook 'cia_infra', git: 'git@github.com:chef-cookbooks/cia_infra.git'
cookbook 'oc-users', git: 'git@github.com:opscode-cookbooks/oc-users.git'
cookbook 'route53', git: 'https://github.com/cwebberOps/route53.git', branch: 'pdb/nononokogiri'
cookbook 'brightbox-ruby', github: 'Padgett/brightbox-ruby-cookbook', branch: 'boolean-generate-binstubs'
cookbook 'habitat-build', git: 'https://github.com/chef-cookbooks/habitat-build'
cookbook 'expeditor-build', git: 'git@github.com:chef-cookbooks/expeditor-build.git'
