name 'omnitruck'
maintainer 'Chef Software'
maintainer_email 'cookbooks@chef.io'
license 'Apache2'
description 'Installs/Configures omnitruck'
long_description 'Installs/Configures omnitruck'
version '0.4.18'

depends 'delivery-sugar'
depends 'cia_infra'
depends 'habitat', '~> 0.4.0'
depends 'build-essential'

issues_url 'https://github.com/chef/omnitruck/issues'
source_url 'https://github.com/chef/omnitruck'
