#!/bin/sh
#
exec 2>&1

export OMNITRUCK_YAML="/hab/svc/omnitruck/config/config.yml"
export SSL_CERT_FILE="$(hab pkg path core/cacerts)/ssl/cert.pem"

cd $"$(hab pkg path {{pkg.origin}}/omnitruck)"/app

exec bundle exec ./poller -e production

# TODO: Figure out why sleep ends script
exec sleep 5m
