#!/bin/bash

export HOME="/hab"

echo "Copying poller config.yml"
cp -v {{pkg.svc_config_path}}/poller_config.yml {{pkg.svc_static_path}}/config/config.yml

echo "Copying unicorn.rb"
cp -v {{pkg.svc_config_path}}/unicorn.rb {{pkg.svc_static_path}}/config/unicorn.rb

echo "Making poller metadata directory"
mkdir -p {{cfg.poller.metadata_dir}}

echo "Running poller to seed omnitruck data"
(cd {{pkg.svc_static_path}} && bundle exec ./poller -e production)
