#!/bin/bash

export GEM_HOME="{{pkg.svc_static_path}}/vendor/bundle/ruby/2.3.0"
export GEM_PATH="$(hab pkg path core/ruby)/lib/ruby/gems/2.3.0:$(hab pkg path core/bundler):$GEM_HOME"
export LD_LIBRARY_PATH="$(hab pkg path core/gcc-libs)/lib"
export SSL_CERT_FILE="$(hab pkg path core/cacerts)/ssl/cert.pem"

cd {{pkg.svc_static_path}}

exec 2>&1
exec bin/unicorn -E {{cfg.app_environment}} -c {{pkg.svc_static_path}}/config/unicorn.rb {{pkg.svc_static_path}}/config.ru
