---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: omnitruck-virtual-service
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            kube:
              ref:
                name: omnitruck
                namespace: omnitruck
              port: 8080
        options:
          autoHostRewrite: true 
