apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: omnitruck
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: omnitruck
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
