worker_rlimit_nofile = 8192
worker_processes = "auto"
upstream_server = "unix:/hab/svc/omnitruck/var/unicorn.sock.0"

[http]
sendfile = "on"
tcp_nopush = "on"
tcp_nodelay = "on"
keepalive_timeout = "20s"

[events]
worker_connections = 1024

[proxy_cache_path]
path = "/hab/svc/omnitruck-unicorn-proxy/nginx/proxy"
levels = "1:2"
keys_zone = "omnitruck-cache:50m"
max_size = "1000m"
inactive = "600m"

[server]
listen = 80
proxy_cache = "omnitruck-cache"
